config/routes.rb
GitPipeline::Application.routes.draw do
  root to: "pipelines#index"
  resources :pipelines do
    resources :versions
  end
end

app/views/partials/_git_clone_error.haml
- if err = @git_repo_clone_error
  .alert.alert-warning
    %p= err.message

app/views/partials/_git_commits.haml
- if log.git_commits_available?
  %ul.git-commits
    - log.git_commits.each do |git_commit|
      %li.git-commit{title: git_commit.message_rest}
        %code.sha
          - sha = git_commit.short_sha
          = link_to(sha, linker.commit_url(sha))

        %span.message-first-line<
          = git_commit.message_first_line
          = "..." if git_commit.message_rest.present?

        %span.author-initials{title: git_commit.author_name}
          = "(#{git_commit.author_initials})"

  - if log.more_commits?
    %p.more-git-commits ...

- else
  %p.not-available-git-commits Not available

app/views/partials/_git_log_stats.haml
%ul.git-log-stats
  %li.symbolic-range
    between
    %code
      - ref = log.symbolic_from
      = link_to(ref, linker.ref_url(ref))
    and
    %code
      - ref = log.symbolic_to
      = link_to(ref, linker.ref_url(ref))

  - if log.git_commits_available?
    %li.commits-no
      = link_to(linker.compare_url(log.symbolic_from, log.symbolic_to)) do
        = ">" if log.more_commits?
        = log.git_commits.size
        commit(s)

app/views/partials/_git_submodule_changes.haml
%ul.git-submodule-changes
  - log.aggregate_git_submodule_changes.each do |git_submodule_change|
    %li.git-submodule-change{title: git_submodule_change.path}
      %h3.path
        %span.hole ●
        %span.line &nbsp;
        = git_submodule_change.path

      - linker = linker_factory.linker_for_git_repo(git_submodule_change.git_repo)

      = render partial: "partials/git_log_stats",
        locals: {log: git_submodule_change.git_log, linker: linker}

      = render partial: "partials/git_commits",
        locals: {log: git_submodule_change.git_log, linker: linker}

app/views/partials/_pipeline_description.haml
.pipeline
  %h1= pipeline.name

  %p.description
    - if lfa = pipeline.git_repo.last_fetched_at
      %span.last-fetched
        = "Last fetched #{time_ago_in_words(lfa)} ago"
        = link_to("(refetch)", force_fetch: "1")

    %span.github-url
      from
      - url = pipeline.git_repo.remote_url
      = link_to(url, url)

  %p.switch-links
    = link_to "Current", pipeline_path(pipeline)
    = link_to "Older",   pipeline_versions_path(pipeline)

  = render partial: "partials/git_clone_error"